### ISSUE TITLE
Adapting to use with trafik v2

### ISSUE THREAD

**Issue by Snuffy2** [iainbullock/tesla-http-proxy-docker#18]
So I've actually gotten this to work behind traefik v2 but it does require both the tesla-http-proxy-docker and a nginx docker. Traefik can redirect (similar to nginx proxy_pass) but I don't believe it can host files which is needed for the `com.tesla.3p.public-key.pem`. However, it may still be possible without nginx but I'm not sure.

A couple of questions:
1. What are the lines in the nginx conf that direct everything but traffic at the root to the tesla proxy?
2. Is there anyway to access the com.tesla.3p.public-key.pem file from either the flask web server on port 8099 or the tesla proxy server on port 443?

My current config using traefik for reverse proxy and for SSL.

Docker Compose:
```
services:
  tesla-proxy:
    depends_on:
      traefik:
        condition: service_healthy
    image: iainbullock/tesla_http_proxy:latest
    container_name: tesla-proxy
    hostname: tesla-proxy
    restart: unless-stopped
    networks:
      - default
    environment:
      - TZ=$TZ
      - "CLIENT_ID=<redacted>"
      - "CLIENT_SECRET=<redacted>"
      - DOMAIN=tesla-proxy.domain.com
      - PROXY_HOST=10.100.200.50
      - "REGION=North America, Asia-Pacific"
    stdin_open: true
    tty: true
    entrypoint: "/app/run.sh"
    working_dir: /app
    volumes:
      - $LOCALTIME
      - ${APPDATA}/tesla-proxy/data:/data
      - ${APPDATA}/tesla-proxy/share:/share

  tesla-proxy-nginx:
    depends_on:
      tesla-proxy:
        condition: service_started
    image: nginx:latest
    container_name: tesla-proxy-nginx
    hostname: tesla-proxy-nginx
    restart: unless-stopped
    networks:
      - traefik_proxy
      - default
    volumes:
      - $LOCALTIME
      - ${APPDATA}/tesla-proxy/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ${APPDATA}/tesla-proxy/share:/share
    environment:
      TZ: $TZ
    labels:
      - traefik.enable=true
      - "traefik.http.routers.tesla-proxy-ext.rule=Host(`tesla-proxy.$DOMAIN`)"
      - traefik.http.routers.tesla-proxy-ext.entrypoints=websecure
      - traefik.http.routers.tesla-proxy-ext.service=tesla-proxy
      - traefik.http.services.tesla-proxy.loadbalancer.server.port=80
```

Nginx Conf:
```
server {
    listen 80;
    listen [::]:80;
    server_name tesla-proxy.domain.com;

    proxy_buffering off;

    resolver 127.0.0.11;
    set $target __PROXYHOST__;

    # temporary Flask app for initial auth
    #location / {
    #    proxy_pass http://tesla-proxy:8099;
    #}

    # Changed to this one once I shutdown the Flask app
    location / {
        proxy_pass https://tesla-proxy:443;
    }
 
    # static public key for Tesla
    location /.well-known/appspecific/com.tesla.3p.public-key.pem {
        root /share;
        try_files /com.tesla.3p.public-key.pem =404;
    }

}
```
