### ISSUE TITLE
For the wee bit docker impaired

### ISSUE THREAD

**Issue by yurgh** [iainbullock/tesla-http-proxy-docker#2]
My container keeps restarting and the data directory doesn't show up, so I can't edit config.sh.

Error message is:
```
$ docker compose up teslaproxy
[+] Running 1/0
 ⠿ Container teslaproxy  Recreated                                                                                                                              0.0s
Attaching to teslaproxy
teslaproxy exited with code 0

```
Any pointers to get the container running? The is no info from docker log, and can't attach to the container since it's restarting.
The relevant part of my docker-compose.yml:
```
  teslaproxy:
    restart: unless-stopped
    container_name: teslaproxy
    image: iainbullock/tesla_http_proxy
    network_mode: host
    volumes:
      - '/opt/teslaproxy/data:/data'
```

**Comment by yurgh** [comment]
After adding the entrypoint it runs, and creates the files in data. 
For reference; the complete config (without my other containers) is now:
```
version: '3'
services:
  teslaproxy:
    restart: 'no'
    container_name: teslaproxy
    image: iainbullock/tesla_http_proxy
    entrypoint: "/app/run.sh"
    volumes:
      - '/opt/teslaproxy/data:/data'
```
Running it again after filling in the fields in config.sh yields:
```
$ docker compose up teslaproxy
[+] Running 1/0
 ⠿ Container teslaproxy  Created                                                                                                                                0.0s
Attaching to teslaproxy
teslaproxy  | Configuration Options are:
teslaproxy  | CLIENT_ID=1c1f3b6bff4a-4bc0-bec6-8eb8f3ec39d2
teslaproxy  | CLIENT_SECRET=Not Shown
teslaproxy  | DOMAIN=tesla.host.info
teslaproxy  | PROXY_HOST=10.0.0.80
teslaproxy  | REGION=Europe, Middle East, Africa
teslaproxy  | Setting up for first launch
teslaproxy  | Setting up GnuPG and password-store
teslaproxy  | gpg: keybox '/data/gnugpg/pubring.kbx' created
teslaproxy  | gpg: /data/gnugpg/trustdb.gpg: trustdb created
teslaproxy  | gpg: directory '/data/gnugpg/openpgp-revocs.d' created
teslaproxy  | gpg: revocation certificate stored as '/data/gnugpg/openpgp-revocs.d/B723A4E0720CB1AB4B2F49E23B3F0489842E9045.rev'
teslaproxy  | gpg: checking the trustdb
teslaproxy  | gpg: marginals needed: 3  completes needed: 1  trust model: pgp
teslaproxy  | gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
teslaproxy  | gpg: next trustdb check due at 2027-03-13
teslaproxy  | /data/gnugpg/pubring.kbx
teslaproxy  | ------------------------
teslaproxy  | pub   ed25519 2024-03-13 [SC] [expires: 2027-03-13]
teslaproxy  |       B723A4E0720CB1AB4B2F49E23B3F0489842E9045
teslaproxy  | uid           [ultimate] myself
teslaproxy  | sub   cv25519 2024-03-13 [E]
teslaproxy  |
teslaproxy  | created directory: '/data/password-store/'
teslaproxy  | Password store initialized for myself
teslaproxy  | Generating self-signed SSL certificate
teslaproxy  | -----
teslaproxy  | Generating keypair
teslaproxy  | -----BEGIN PUBLIC KEY-----
teslaproxy  | MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEUBzCzMpLvefVioAQ72FwUbC9o7iT
teslaproxy  | fcygjebFlhhTTvQLOa9pLpmzQ0NkViRtEsuIj2mmT+wpcWAqkuqqvtd8XQ==
teslaproxy  | -----END PUBLIC KEY-----
teslaproxy  | Starting temporary Python app for authentication flow. Delete /data/access_token to force regeneration in the future
teslaproxy  | Traceback (most recent call last):
teslaproxy  |   File "/app/run.py", line 14, in <module>
teslaproxy  |     CLIENT_ID = os.environ['CLIENT_ID']
teslaproxy  |                 ~~~~~~~~~~^^^^^^^^^^^^^
teslaproxy  |   File "<frozen os>", line 679, in __getitem__
teslaproxy  | KeyError: 'CLIENT_ID'
teslaproxy exited with code 1
 ```
(I've altered the id and host here, you never know what men in trenchcoats might be up to on the internet!)
It seems like the environment variables set in config.sh/app.sh isn't available in the environment in app.py? Next attempt also fails on the same line in app.py 

But feels like getting closer :)
