### ISSUE TITLE
Configuration options not set in /data/config.sh

### ISSUE THREAD

**Issue by peter-funktionIT** [iainbullock/tesla-http-proxy-docker#37]
I am unable to get the initial setup working, I immediately get this output when trying to run the container through docker compose:

```
root@raspberrypi:~# docker compose up --force-recreate --build tesla_http_proxy
[+] Running 1/1
 ✔ Container tesla_http_proxy  Recreated    1.0s
Attaching to tesla_http_proxy
tesla_http_proxy  | Configuration options not set in /data/config.sh, exiting
tesla_http_proxy exited with code 0
```

What am I doing wrong?
I think the setup for nginx in my SWAG-container should work, but I don't seem to even get to that step.

This is my docker-compose:

```
services:
  tesla_http_proxy:
    container_name: tesla_http_proxy
    image: "iainbullock/tesla_http_proxy:latest"
    environment:
      - TZ='Europe/Stockholm'
      - CLIENT_ID='REDACTED'
      - CLIENT_SECRET='ta-secret.REDACTED'
      - DOMAIN='REDACTED' # Public FQDN
      - PROXY_HOST='REDACTED' # Local hostname (not IP) of this docker host
      - REGION='Europe, Middle East, Africa' # Change to match your region
    stdin_open: true
    tty: true

    entrypoint: "/app/run.sh"
    working_dir: /app

    volumes:
      - /home/tesla_http_proxy/data:/data
      # Webserver root for the $DOMAIN virtual server. Change the path according to your webserver setup. Path must exist or this container won't start
      - type: bind
        source: /home/swag/config/teslawww
        target: /share/nginx
      # Path to tesla_http_proxy directory inside /config on Home Assistant instance. Change according to your HA setup. Path must exist or this container won't start
      - type: bind
        source: /home/hass/config/tesla_http_proxy
        target: /share/home-assistant

    network_mode: bridge
    ports:
      - 4430:443
      - 8099:8099
    restart: "no"
```
