### ISSUE TITLE
Nginx Proxy Manager setup

### ISSUE THREAD

**Issue by xPand4B** [iainbullock/tesla-http-proxy-docker#40]
It would be very cool and usefull to have a guide/version of this container for a setup using the [Nginx Proxy Manager](https://nginxproxymanager.com/).

Exposing the service to some port and e.g. having a new env var "SERVER_TYPE" with values like "local" and "NPM" could be the activator for this. This way it should be possible to just use this web server instead of booting up another one just for this client.

Any suggestions?

**Comment by tux43** [comment]
I've just been writing up a [guide](https://www.smartmotion.life/2024/04/23/tesla-custom-integration-with-home-assistant-on-docker/) 

Any feedback is very welcome.!

**Comment by mekaneck** [comment]
I'm running this using NPM only without spinning up a separate NGINX server. I can try to write up a guide over the weekend. The key is to place the `com.tesla.3p.public-key.pem` file into your NPM's data folder under a subfolder called `tesla-http-proxy` and then when you add a proxy host in the GUI you add this to the "advanced" tab:

```
location /.well-known/appspecific/com.tesla.3p.public-key.pem {
        root /data/tesla_http_proxy;
        try_files /com.tesla.3p.public-key.pem =404;
}
```

**Comment by mekaneck** [comment]
Here is my docker-compose, note I use `${DOCKER_DATA_DIR}` and `${TZ}` variables for my directory path and timezone, respectively. Also note I use an external network as per the recommended practices so I don't have to publish ports on my host and instead I use the `expose` argument (ref: [NPM documentation](https://nginxproxymanager.com/advanced-config/#best-practice-use-a-docker-network)). (`expose` may not even be necessary, it's possible it could be eliminated entirely, I haven't tried.)

```yaml
version: '3.0'

networks:
  default:
    external: true
    name: same_external_network_as_NPM_container
    
services:
  tesla_http_proxy:
    container_name: tesla_http_proxy
    image: "iainbullock/tesla_http_proxy:latest"
 
    environment:
      - TZ=${TZ}
      
    stdin_open: true
    tty: true         
   
    entrypoint: "/app/run.sh"
    working_dir: /app

    volumes:
      - ${DOCKER_DATA_DIR}/tesla_http_proxy:/data
      # Webserver root for the $DOMAIN virtual server. Change the path according to your webserver setup. Path must exist or this container won't start
      - ${DOCKER_DATA_DIR}/nginx-proxy-manager/data/tesla_http_proxy:/share/nginx
      # Path to tesla_http_proxy directory inside /config on Home Assistant instance. Change according to your HA setup. Path must exist or this container won't start
      - ${DOCKER_DATA_DIR}/homeassistant/config/tesla_http_proxy:/share/home-assistant
    expose:
      - 443
      - 8099

    restart: unless-stopped  
```

First you can set up a new proxy host on NPM. Assuming your top level domain is `example.com` you can fill in the NPM proxy host details like this:
 - Domain Names: `tesla-proxy.example.com`
 - Scheme: `https`
 - Forward Hostname/IP: `tesla_http_proxy` (should match the container's name if you use the external network recommended practice; otherwise use the IP of the tesla http proxy container you're going to spin up)
 - Forward Port: `8099`

Go to the SSL tab:
 - select a certificate
 - choose "force SSL"

Go to the "Advanced" tab, and enter the following:
 - ```
   location /.well-known/appspecific/com.tesla.3p.public-key.pem {
            root /data/tesla_http_proxy;
            try_files /com.tesla.3p.public-key.pem =404;
   }
   ```

Then follow the instructions in the regular setup guide. After you shut down the flask server, you'll need to go back into your NPM proxy host settings and change the "Forward Port" that we set earlier from `8099` to `443`.

I did all this with the initial release of the docker file, so the steps have changed a little and I think I've updated what needs updating. But if you run into issues let me know. Sorry it's not a complete guide, it just has the unique points for NPM.

**Comment by andjo** [comment]
Just managed to get this setup with the above instructions from @mekaneck.  😍
The only snag was that I needed to use  `http` scheme for the `8099` port, and then switch to `https` for 443.

Now I'm back in business with Home Assistant + Tesla Custom Integration in a Proxmox VM (HAOS), with Tesla HTTP Proxy Docker and NPM managed by Portainer in a separate VM.

In this environment I had to copy `selfsigned.pem` manually to Home Assistant.

**Comment by tux43** [comment]
I’ve tried to document all of it - happy for feedback.

https://www.smartmotion.life/2024/04/23/tesla-custom-integration-with-home-assistant-on-docker/

**Comment by mekaneck** [comment]
Thanks for the feedback @andjo I've updated my previous post with those changes. 

@tux43 - this discussion is specific to NGINX Proxy Manager, which is a an implementation of NGINX that uses a GUI and therefore has some restrictions on what customization is possible compared to the vanilla NGINX. Your guide appears to pertain to vanilla NGINX.

**Comment by Chacsam** [comment]
> Just managed to get this setup with the above instructions from @mekaneck. 😍 The only snag was that I needed to use `http` scheme for the `8099` port, and then switch to `https` for 443.
> 
> Now I'm back in business with Home Assistant + Tesla Custom Integration in a Proxmox VM (HAOS), with Tesla HTTP Proxy Docker and NPM managed by Portainer in a separate VM.
> 
> In this environment I had to copy `selfsigned.pem` manually to Home Assistant.

Hi,

Do I get it right that you installed the Tesla HTTP Proxy Docker on the same VM as your NPM (while Home assistant is on another one)?
I am trying to make something similar

**Comment by andjo** [comment]
You got it right @Chacsam. 

The only problem with HA in an other location is the bind mount that is trying to point to a location in the HA configuration directory. I created a dummy directory for that, and after the `selfsigned.pem` was generated, I copied that file to the HA installation at  `/config/tesla_http_proxy/selfsigned.pem` and pointed to that when doing the setup in HA.

My volumes looks like this:
```yaml
    volumes:
      - /opt/tesla-http-proxy:/data
      - /opt/proxy-manager/data/tesla-http-proxy:/share/nginx
      - /opt/tesla-http-proxy-homeassistant/config/tesla_http_proxy:/share/home-assistant # for selfsigned.pem, only used during setup
```

**Comment by iainbullock** [comment]
@tux43 Many thanks for creating the blog. I will refer to it in the Readme

**Comment by iainbullock** [comment]
@Chacsam @xPand4B @mekaneck Just catching up on this Issue. Can I close this one yet?

**Comment by Chacsam** [comment]
Sorry guys, but I am still not there yet.

So, my setup is as follow:
- NPM runs on 192.168.1.210
- Home assistant (docker) on 192.168.1.211

I have successfully run the following docker compose on 210 (NPM)
```
version: '3.0'

networks:
  default:
    external: true
    name: npm_proxy_default
    
services:
  tesla_http_proxy:
    container_name: tesla_http_proxy
    image: "iainbullock/tesla_http_proxy:latest"
 
    environment:
      - TZ='Europe/Amsterdam'
      
    stdin_open: true
    tty: true         
   
    entrypoint: "/app/run.sh"
    working_dir: /app

    volumes:
      - /home/apps/tesla_http_proxy:/data
      - /home/apps/npm_proxy/data/tesla_http_proxy:/share/nginx
      - /home/apps/ha_proxy/config/tesla_http_proxy:/share/home-assistant
    expose:
      - 443
      - 8099

    restart: unless-stopped
```

My NPM setup looks like this:
![image](https://github.com/iainbullock/tesla-http-proxy-docker/assets/28670803/f2bd4d11-775e-4fb8-a1ed-7ab612465001)
![image](https://github.com/iainbullock/tesla-http-proxy-docker/assets/28670803/ab219014-ee83-4540-93e3-47ab6a155a3f)
![image](https://github.com/iainbullock/tesla-http-proxy-docker/assets/28670803/90543346-06a7-4e9a-98f8-3855d4a6bd7c)

I have changed the config.sh file as per instruction.

Rerun the docker container and can find the pem files (on my 210 NPM device):
- com.tesla.3p.public-key.pem in the `apps/npm_proxy/data/tesla_http_proxy` folder
- selfsigned.pem is the `apps/ha_proxy/config/tesla_http_proxy` (copied in my config folder op the HA 211 device)
- a few files and folders in the 'apps/tesla_http_proxy'

When I follow the instructions and "enter the URL of your FQDN into a web browser." 
I just get a 502 Bad Gateway, openresty  Error.

Where did I miss?

**Comment by iainbullock** [comment]
Sorry for delay in response. I'm not familiar with the NPM method, however I make the following comments / suggestions:

- The Flask server is not receiving a connection as there are no logs after [07:06:36] werkzeug:INFO: Press CTRL+C to quit
- The 502 Bad Gateway error happens when you connect to the FQDN but no service is listening, which aligns withthe above observation
- Your Custom NGinx config has the location block for the public key, but not the redirect to the Flask server. You also need a location block like this:

    location / {
        proxy_pass http://192.168.0.3:8099; # Change to hostname or IP of your Docker host
    }

**Comment by Chacsam** [comment]
> Sorry for delay in response. I'm not familiar with the NPM method, however I make the following comments / suggestions:
> 
> * The Flask server is not receiving a connection as there are no logs after [07:06:36] werkzeug:INFO: Press CTRL+C to quit
> * The 502 Bad Gateway error happens when you connect to the FQDN but no service is listening, which aligns withthe above observation
> * Your Custom NGinx config has the location block for the public key, but not the redirect to the Flask server. You also need a location block like this:
>   location / {
>   proxy_pass http://192.168.0.3:8099; # Change to hostname or IP of your Docker host
>   }

Hi,

Thanks for the response.
In my understanding, the base NPM feature acts as the `location /` block.
I did gave your suggestion a try, adapting the "Custom Nginx Configuration" as below, but it didn't change anything.

```
    location / {
        proxy_pass http://192.168.1.210:8099; 
    }

    # static public key for Tesla
    location /.well-known/appspecific/com.tesla.3p.public-key.pem {
        root /usr/share/nginx/tesla_http_proxy;
        try_files /com.tesla.3p.public-key.pem =404;
    }
```

I have another container running on my "210" device which is can be accessed via a NPM config, so that's not a problem either

**Comment by iainbullock** [comment]
You don't get any more proxy logs either? Anything in NGinx logs?

Looks like something is blocking the connection.

How about connecting to the container directly http://172.19.0.5:8099 from a browser (not a permanent solution as the IP address may change)

**Comment by Chacsam** [comment]
> You don't get any more proxy logs either? Anything in NGinx logs?
> 
> Looks like something is blocking the connection.
> 
> How about connecting to the container directly http://172.19.0.5:8099 from a browser (not a permanent solution as the IP address may change)

Connecting to the container directly from a browser gives ERR_CONNECTION_TIMED_OUT

**Comment by iainbullock** [comment]
Umm, not sure. 

Is the Flask Server still running, what are the latest logs from the container?

Do you still have this:
[07:06:36] main:INFO: *** Starting Flask server... ***
[07:06:36] werkzeug:INFO: WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8099
 * Running on http://172.19.0.5:8099
[07:06:36] werkzeug:INFO: Press CTRL+C to quit

Maybe try to connect from inside the container itself. Get a command line using

docker exec -it <mycontainer> bash # you can get <mycontainer> using docker ps

then execute
wget http://127.0.0.1:8099 

see if that connects

**Comment by Chacsam** [comment]
First, thanks a lot for looking with me.

I restarted the container to have a clean start.

Container logs still stops with:
```
Configuration Options are:
CLIENT_ID=379680272824-xxxx-xxxx-xxxxxxxxb006
CLIENT_SECRET=Not Shown
DOMAIN=txxxx.vxxxx.be
PROXY_HOST=Proxy
REGION=Europe, Middle East, Africa
Found existing keypair
Starting temporary Python app for authentication flow. Delete /data/access_token to force regeneration in the future
[10:06:17] main:INFO: *** Starting Flask server... ***
[10:06:17] werkzeug:INFO: WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8099
 * Running on http://172.19.0.5:8099
[10:06:17] werkzeug:INFO: Press CTRL+C to quit
```

The wget within the docker downloads an index.html that looks correct
```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <style>
        body {
            font-family: sans-serif;
            text-align: center;
        }

        div.content {
            width: 100%;
            padding: 10px;
        }

        button {
            padding: 10px;
            font-size: 14px;
            width: 300px;
        }
    </style>
</head>

<body>
    <h2>Tesla HTTP Proxy setup</h2>
    <hr>
    <div class="content">
        <a href="https://auth.tesla.com/oauth2/v3/authorize?&client_id=379680272824-xxxx-xxxx-xxxxxxxxb006&locale=en-US&prompt=login&redirect_uri=https://[--MY FQDN--]/cal
            target="_blank"><button type="button">1. Generate OAuth token</button></a>
    </div>

    <div class="content">
        <a href="https://[--MY FQDN--]/.well-known/appspecific/com.tesla.3p.public-key.pem" target="_blank"><button
                type="button">2. Test public key endpoint</button></a>
    </div>
    <div class="content">
        <a href="register-partner-account"><button type="button">3. Register Partner account<br />
                (Make sure test 2 works first)</button></a>
    </div>
    <div class="content">
        <a href="https://tesla.com/_ak/[--MY FQDN--]" target="_blank"><button type="button">4. Enrol private key into your
                vehicle</button></a>
    </div>
    <div class="content">
        <a href="shutdown"><button type="button">5. Shutdown Flask server</button></a>
    </div>
</body>

</html>
```

**Comment by iainbullock** [comment]
No problem! 

Can you now connect by running the same command on the docker host, e.g.

wget http://192.168.1.210:8099

Or wget http://172.19.0.5:8099

If not something in the npm setup is blocking the connection

**Comment by Chacsam** [comment]
Getting there...

wget http://172.19.0.5:8099/ works

wget http://192.168.1.210:8099 gives
```
Connecting to 192.168.1.210:8099 (192.168.1.210:8099)
wget: can't connect to remote host (192.168.1.210): Connection refused
```

**Comment by iainbullock** [comment]
The PROXY_HOST in config.sh is used to sign selfsigned.pem. It doesn't explain why you can't make a connection to the Flask Server from outside the container

Things you could try is:
- Check nothing else on your docker host is using ports 8099 (and 443 for that matter)
- Change the network_mode in docker compose to host (you don't need the port redirection then)

**Comment by Chacsam** [comment]
NPM is on port 443, that one I can hardly change.
I don't see anything on port 8099.

Network_mode on host gives (a normal error)
```
Starting Tesla HTTP Proxy

Do not listen on a network interface without adding client authentication. Unauthorized clients may
be used to create excessive traffic from your IP address to Tesla's servers, which Tesla may respond
to by rate limiting or blocking your connections.
2024-05-04T09:04:46Z [debug] Creating proxy
2024-05-04T09:04:46Z [info ] Listening on 0.0.0.0:443
2024-05-04T09:04:46Z [error] Server stopped: listen tcp 0.0.0.0:443: bind: address already in use
```

**Comment by iainbullock** [comment]
Ok so port 443 is already used on the host. The container uses 443 internally for the proxy, but the standard docker compose remaps it to 4430 on the host. When you tried earlier to 'declare ports the standard way in my docker-compose' did you remap 443 to 4430 or to 443?

**Comment by Chacsam** [comment]
to 443, shall I remap to 4430?

**Comment by iainbullock** [comment]
Yes please try that to avoid clash with the host

**Comment by Chacsam** [comment]
You mean this, right?

```
services:
  tesla_http_proxy:
    container_name: tesla_http_proxy
    image: "iainbullock/tesla_http_proxy:latest"
    network_mode: host
    ports:
      - '8089:8089' 
      - '4430:4430'
```

I still have the same bind error

**Comment by iainbullock** [comment]
Sorry I should have said change back to bridge mode as host mode won't work, and remap as follows:

    network_mode: bridge
    ports:
      - 8089:8089
      - 4430:443

**Comment by Chacsam** [comment]
Still no luck.

I did clean everything up for a fresh start,

Container runs
Docker ps says:
```
CONTAINER ID   IMAGE                                 COMMAND                  CREATED             STATUS                PORTS                                                                                            NAMES
8f9d014a6184   iainbullock/tesla_http_proxy:latest   "/app/run.sh"            11 minutes ago      Up 9 minutes          0.0.0.0:8089->8089/tcp, :::8089->8089/tcp, 0.0.0.0:4430->443/tcp, :::4430->443/tcp               tesla_http_proxy
0f3c4efd45cd   jc21/nginx-proxy-manager:latest       "/init"                  About an hour ago   Up About an hour      0.0.0.0:80-81->80-81/tcp, :::80-81->80-81/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp             NPMproxy
...
```

Log says:
```
Setting up GnuPG and password-store
gpg: keybox '/data/gnugpg/pubring.kbx' created
gpg: /data/gnugpg/trustdb.gpg: trustdb created
gpg: directory '/data/gnugpg/openpgp-revocs.d' created
gpg: revocation certificate stored as '/data/gnugpg/openpgp-revocs.d/xxxxxxxx.rev'
gpg: checking the trustdb
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: next trustdb check due at 2027-05-04
/data/gnugpg/pubring.kbx
------------------------
pub   ed25519 2024-05-04 [SC] [expires: 2027-05-04]
      xxxxxxxxxx
uid           [ultimate] myself
sub   cv25519 2024-05-04 [E]

created directory: '/data/password-store/'
Password store initialized for myself
Generating keypair
-----BEGIN PUBLIC KEY-----
xxxx+ORZ36DQNxxxxxxxxxxCABw1j6
xxxxxxxxx//xxxx==
-----END PUBLIC KEY-----
SSL certificate does not exist
Generating self-signed SSL certificate
-----
Starting temporary Python app for authentication flow. Delete /data/access_token to force regeneration in the future
[09:58:23] main:INFO: *** Starting Flask server... ***
[09:58:23] werkzeug:INFO: WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8099
 * Running on http://172.17.0.4:8099
[09:58:23] werkzeug:INFO: Press CTRL+C to quit
```

But still the same http 502 error and no access from within container 
```
8f9d014a6184:/app# wget http://192.168.11.210:8089
Connecting to 192.168.11.210:8089 (192.168.11.210:8089)
wget: error getting response: Connection reset by peer
```
I also fully turned off the firewall on Proxmox at datacenter level to test a few minutes, but that didn't change anything

**Comment by iainbullock** [comment]
I've run out of ideas to be honest. Not using Proxmox or NPM makes difficult for me to offer other suggestions. There is something blocking connections between the host and the container. If you do manage to figure it out please update here

**Comment by Chacsam** [comment]
I figured so, am a bit getting desperate as well. Again, thanks for trying all this time.
I will update here if I find light

**Comment by Chacsam** [comment]
No solution, but additional information for anyone who would have a clue.
I have created the docker in a brand new proxmox CT with only Docker and Portainer on it.

I made a quick and dirty setup on host network:

```
version: '3.0'
  
services:
  tesla_http_proxy:
    container_name: tesla_http_proxy
    image: "iainbullock/tesla_http_proxy:latest"
    network_mode: host
    
    environment:
      - TZ='Europe/Amsterdam'
      
    stdin_open: true
    tty: true         
   
    entrypoint: "/app/run.sh"
    working_dir: /app

    volumes:
      - /root/proxy_app/tesla_http:/data
      - /root/proxy_app/nginx_share:/share/nginx
      - /root/proxy_app/ha_config:/share/home-assistant

    restart: unless-stopped
```
I can access the tesla_http_proxy page from the host on which NPM is running:
```
wget http://192.168.11.225:8099
--2024-05-04 13:53:42--  http://192.168.11.225:8099/
Connecting to 192.168.11.225:8099... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1704 (1.7K) [text/html]
Saving to: 'index.html'
```
Which is nicely registered in the log of tesla_http_proxy
`[11:53:42] werkzeug:INFO: 192.168.11.210 - - [04/May/2024 11:53:42] "GET / HTTP/1.1" 200 -`

But I cannot access it from my Desktop browser, neither on http://192.168.11.225:8099 nor via NPM proxy
I am getting a ERR_CONNECTION_TIMED_OUT from the browser and a 504 gateway timeout via NPM

If I disable the Proxmox Firewall at Datacenter level (there is no firewall activated at CT level) the timeout becomes  ERR_CONNECTION_REFUSED (ie a 502 via NPM)

**Comment by mekaneck** [comment]
@Chacsam maybe you better start at the basics: what docker network settings to you use for NPM, and what docker network settings do you use for containers that you successfully have proxied with NPM?

**Comment by Chacsam** [comment]
> @Chacsam maybe you better start at the basics: what docker network settings to you use for NPM, and what docker network settings do you use for containers that you successfully have proxied with NPM?

Hi @mekaneck 
My NPM manages a dozen of proxy hosts successfully forwarding traffic to my Synology NAS or different Proxmox CT's or VM's with applications such as Nextcloud, Home Assistant, Grocy,, Immich...
Rhis is really the first one I cannot get connected.
So I believe the basics are right, but any suggestion is welcome

**Comment by mekaneck** [comment]
@Chacsam  Yes I figured as much. Can you share how those are set up so that I can make some suggestions for setting up this container?

**Comment by Chacsam** [comment]
@mekaneck 
My base setup has been described above: [https://github.com/iainbullock/tesla-http-proxy-docker/issues/40#issuecomment-2088042547](https://github.com/iainbullock/tesla-http-proxy-docker/issues/40#issuecomment-2088042547)

My NPM docker-compose looks like this
```
services:
  app:
    container_name: NPMproxy
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    environment:
      # Mysql/Maria connection parameters:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "xxxxxxx"
      DB_MYSQL_NAME: "npm"
      TZ: "Europe/Amsterdam"
    volumes:
      - /home/frederic/npm_proxy/data:/data
      - /home/frederic/npm_proxy/letsencrypt:/etc/letsencrypt
```
NPM is running on the npm_proxy_default network.
