### ISSUE TITLE
Traefik support - Proxy HTTP support for external reverse proxy

### ISSUE THREAD

**Issue by XxTopKillerzZ** [iainbullock/tesla-http-proxy-docker#50]
Hello,

Congratulations for making all this be possible.
I recently managed to make this work but I had some troubles. 
I use traefik for reverse proxy all my services so using a selfsigned certificate only for this service is a pain. I managed to make all this work using starting from the #18 
If anyone wants feel free to reply and I will redact my domains and place the configs in here.
Basically traefik proxies tesla.mydomain.com to nginx which then serves the tesla certificate and the flash app(disabled after setup).
Traefik also proxies teslaproxy.internal.mydomain.com to tesla-proxy container trough port 443 but I need to setup a TCP router with TLS passtrough for the proxy to accept my certificate

Also HomeAssistant and Traefik+Proxy are on different VM's so mounting the certificate file is a pain, I managed to move it by hand since it shouldn't change after inicial setup.

What I propose is an option to make tesla-proxy listen only in port 80 for traefik to handle certificate generation via ACME like all the other services
Feel free to tell me if you want to work to make this happen

**Comment by iainbullock** [comment]
Please describe the instructions as it might be useful to others. I am not knowlegable about Traefik so can't add much here. 

Regarding having the proxy listen on port 80, can this be achieved by changing docker-compose-yml? e.g:

```
ports:
      - 4430:443

to 

ports:
      - 80:443
```

**Comment by XxTopKillerzZ** [comment]
Hello,

I can do that, in fact I don't even have to map any ports in tesla-proxy container because the connections are made to traefik first. 
The protocol needs to be changed from https to http because tesla-proxy <-> traefik connection is internal to the docker network so normally it is just http.


Docker-Compose file
```
services:
  tesla-proxy:
    image: iainbullock/tesla_http_proxy:latest
    container_name: tesla-proxy
    hostname: tesla-proxy
    restart: unless-stopped
    networks:
      - traefik
    stdin_open: true
    tty: true
    entrypoint: "/app/run.sh"
    working_dir: /app
    volumes:
      - tesla_http_proxy:/data
      - tesla_http_proxy:/share

    labels:
      - traefik.enable=true
      - traefik.tcp.routers.tesla-proxy.rule=HostSNI(`internal.tesla.domain.com`) #DNS only mapped in internal DNS server
      - traefik.tcp.routers.tesla-proxy.entrypoints=websecure
      - traefik.tcp.routers.tesla-proxy.tls=true
      - traefik.tcp.routers.tesla-proxy.tls.passthrough=true
      - traefik.tcp.routers.tesla-proxy.service=tesla-proxy
      - traefik.tcp.services.tesla-proxy.loadbalancer.server.port=443

      # Block outside traffic
      - traefik.tcp.middlewares.tesla-proxy-whitelist-ip.ipwhitelist.sourceRange=192.168.12.0/24,192.168.22.0/24
      - traefik.tcp.routers.tesla-proxy.middlewares=tesla-proxy-whitelist-ip@docker

  tesla-proxy-nginx:
    image: nginx:latest
    container_name: tesla-proxy-nginx
    hostname: tesla-proxy-nginx
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - tesla_http_proxy:/etc/nginx/conf.d
      - tesla_http_proxy:/share
    labels:
      - traefik.enable=true
      - traefik.http.routers.tesla-proxy-nginx.rule=Host(`tesla.domain.com`) #External acessible dns
      - traefik.http.routers.tesla-proxy-nginx.entrypoints=websecure
      - traefik.http.routers.tesla-proxy-nginx.tls=true
      - traefik.http.routers.tesla-proxy-nginx.tls.certresolver=cloudflareNetgere
      - traefik.http.routers.tesla-proxy-nginx.service=tesla-proxy-nginx
      - traefik.http.services.tesla-proxy-nginx.loadbalancer.server.port=80

volumes:
  tesla_http_proxy:
    external: true

networks:
  traefik:
    external: true
```


Default.conf
```
server {
    listen 80;
    listen [::]:80;
    server_name tesla.domain.com; #External acessible dns

    proxy_buffering off;

    resolver 127.0.0.11;
    set $target __PROXYHOST__;

    # temporary Flask app for initial auth (Remove commends then comment after flash shutdown)
#    location / {
#        proxy_pass http://tesla-proxy:8099;
#    }

    # static public key for Tesla (Only thing served by nginx after flash shutdown)
    location /.well-known/appspecific/com.tesla.3p.public-key.pem {
        root /share/nginx;
        try_files /com.tesla.3p.public-key.pem =404;
    }

}
```
