### ISSUE TITLE
refresh token not in the data folder - where to get it? - all the rest works

### ISSUE THREAD

**Issue by frankrox** [iainbullock/tesla-http-proxy-docker#56]
thanks for docker! I have an issue which I hope someone could solve:

Everything works here (I walked through all the steps)  except I can't get the refresh token. Somehow the refresh token is not being put into the data folder. Everything else seems to be working...! I just need to get the refresh token. 

Is there another method to get the refresh token or a solution why it isn't being put in the folder? It doesnt seem to be in the log either. (the partner authentication token is in the logs) The addon readme shows a paste function to paste the URL after you fill in the generate OATH token. I do get that callback url (with the page not found), but ofcourse this is via addon which is not possible with my docker setup and it should be in the folder instead.

My docker-compose file is in volume2/docker/tesla_http_proxy. The config.sh(config4.sh in the meantime, was debugging some other stuff) is read correctly from the data folder (tesla_http_proxy/data) , also the pem file is put in the right folder (/volume2/docker/homeassistant/config/tesla_http_proxy), and the com.tesla.3p.public-key.pem is put into the web folder. Just the refresh token is missing. 

Thanks!

To be complete, here is my docker-compose.yml:

```

version: '3'
volumes:
  tesla_http_proxy:
    external: true
services:   
  tesla_http_proxy:
    container_name: tesla_http_proxy
    restart: always
    image: "iainbullock/tesla_http_proxy:latest"

    environment:
      - TZ=Europe/Amsterdam
      - CLIENT_ID=xxxxxxxxxxxxxxxxxxxxxxx
      - CLIENT_SECRET=xxxxxxxxxxxxxxxxxxxxxxxx
      - DOMAIN=xxxxxxxx # Public FQDN 
      - PROXY_HOST=xxxxxxx # Local hostname (not IP) of this docker host
      - REGION=Europe, Middle East, Africa
      
    stdin_open: true
    tty: true         

    entrypoint: "/app/run.sh"
    working_dir: /app

    volumes:

      - tesla_http_proxy:/data
      # Webserver root for the $DOMAIN virtual server. Change the path according to your webserver setup. Path must exist or this container won't start
      - type: bind
        source: /volume2/web/teslaproxy # Refer to step 2.1
        target: /share/nginx #Do not modify
      # Path to tesla_http_proxy directory inside /config on Home Assistant instance. Change according to your HA setup. Path must exist or this container won't start
      - type: bind
        source: /volume2/docker/homeassistent/config/tesla_http_proxy #Refer to step 5.1
        target: /share/home-assistant #Do not modify
      - /volume2/docker/tesla_http_proxy/data/config4.sh:/data/config4.sh 

    network_mode: bridge
    ports:
      - 4430:443
      - 8099:8099 

volumes: 
  tesla_http_proxy: {}



```
