### ISSUE TITLE
Integrate serving public key? + Caddy docker example

### ISSUE THREAD

**Issue by 3sv** [iainbullock/tesla-http-proxy-docker#58]
Thanks for the great work, got it running from Docker with Caddy webserver for SSL termination and serving the public key during setup. 

The documentation was a bit difficult to follow, given the integration with Nginx and home assistant. On my setup placed the Tesla HTTP Proxy on a VPS, and HA running on another docker instance on a RPI at home.

Is there any reason the flask server is not directly serving the public key for setup purposes? If the flask server would handle this task, the flow would be easier and less dependent on what software is used as webserver or ssl reverse proxy? The end user doesn't has to bother with the path ".well-known/appspecific/com.tesla.3p.public-key.pem" of that certificate as it is created internally already and can be served directly as well? 

Ended up using this Caddy configuration, that allows serving the tasks provided by Flask, as well as the public key, and the Tesla API in one go:
```
tesla.fqdn.com {
	@teslaapi {
		path /api/*
	}

	@publickey path /.well-known/appspecific/com.tesla.3p.public-key.pem

	@flask {
		 not {
			path /.well-known/appspecific/com.tesla.3p.public-key.pem
                	path /api/*
		}
	}

  	reverse_proxy @teslaapi teslaproxy:443 {
		transport http {
			tls_insecure_skip_verify
		}
	}

	handle @publickey {
		rewrite * com.tesla.3p.public-key.pem
	        root /caddy/teslaproxy
		file_server
	}

	handle @flask {
		reverse_proxy teslaproxy:8099
	}
}
```

For reference, the docker-compose used, setting the "teslaproxy" hostname used in the Caddy configration, and the shared directory with the certificate. 
```
teslaproxy:
    container_name: teslaproxy
    image: "iainbullock/tesla_http_proxy"
    restart: unless-stopped
    volumes:
      - /media/Docker/teslaproxy:/data:Z
      - /media/Docker/teslaproxy/nginx:/share/nginx:Z
      - /media/Docker/teslaproxy/ha:/share/home-assistant:Z

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - 443:443
      - 80:80
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile:Z
      - /media/Docker/teslaproxy/nginx:/caddy/teslaproxy:Z
```

Additionally it would make configuration easier if there is just 1 port to expose, that does both the Flask things for setup, and the Tesla API at /api/* directly I suppose? The above Caddy configuration can handle this, but the documentation of Nginx is using two different configs for setup and exposing the Tesla API? 

For others that would use this setup:
- Start caddy, ensure to set DOMAIN, CLIENT_ID, CLIENT_SECRET, REGION either in docker environment or in /media/Docker/teslaproxy/config.sh
- Follow the five steps as served in the flask application, you can do them all from 1 to 5 without restarting. 
- Copy the "selfsigned.pem" from "/media/Docker/teslaproxy/ha" to your home assistant config folder. 
- The necessary information for Tesla custom integration proxy option are printed on the console. Fill in the refresh token, set the url to point to the caddy proxy, and enter the client ID + path to the selfsigned.pem
